### ISSUE TITLE
Custom Post Types / Filtering / Sorting

### ISSUE THREAD

**Issue by rmulr** [ZamzamInc/SwiftyPress#4]
Hey there,

i am new to iOS development and plan to create a WordPress based news reader like app. 

Now on my blog there are some custom post types with shop like items i would like to sort and filter by custom taxonomies.

For e.g a product item. On the WordPress blog i am using a Plugin called Toolset Views listing all these products in a grid like page where a user can paginate and filter through. 

I guess i would have to extend the WordPress SwiftyPress plugin / framework to achieve all these funtionality to my custom post type?

Maybe there is any example or somebody using the framework for such kind of scenario.

thanks in advance

**Comment by basememara** [comment]
A few weeks ago, I exposed a setting to set the prefix of the REST API path called `postRESTPrefix` (1abd9d9).

What this allows you to do is set the REST url path in your `Settings.plist` to point to the custom post path, so the constructed URL would be `/wp-json/post-rest-prefix-like-cars/123`.

It needs to be extended more because it will only grab the post fields that are in common with the main post type, like title, content, categories, tags, etc. This works for the most part, but I’d like to also allow any custom fields to be added to the HTML template and passively retrieve the field value of it exists.

**Comment by basememara** [comment]
A rewritten update has been merged into `master` and `develop` with `readme` instructions and a full working sample app. Please take a look and open a new issue if the issue persists.
